<!doctype html>
<html>
<head>
<title>Login</title>
</head>
<body background="img.jpg">
<p>
<h3 align="center"><font type=Baskerville Old Face size=5 color =white>ONLINE TAMIL MUSICAL PLAY</h3></font>
<form action="" method="POST">
<table align=center>
<tr><td><font size=4 color=#FFE87C><b>Username:</b></td><td> <input type="text" name="user"><br /></font></td></tr>
<tr><td><b><font size=4 color=#FFE87C>Password: </b></td><td><input type="password" name="pass"><br />	</td></tr></font>
<tr><td align=center><input type="submit" value="Login" name="submit" /></td>
<td><p align=center><a href="register.php"><font size=4 color=#FFE87C><b>Signup</b></font></a> </p></td></tr>
</table>
</form>
<center>
	<font color=#FFFFCC>

<?php
if(isset($_POST["submit"])){

if(!empty($_POST['user']) && !empty($_POST['pass'])) {
	$user=$_POST['user'];
	$pass=$_POST['pass'];

	$con=mysql_connect('localhost','root','') or die(mysql_error());
	mysql_select_db('music') or die("cannot select DB");

	$query=mysql_query("SELECT * FROM login WHERE username='".$user."' AND password='".$pass."'");
	$numrows=mysql_num_rows($query);
	if($numrows!=0)
	{
	while($row=mysql_fetch_assoc($query))
	{
	$dbusername=$row['username'];
	$dbpassword=$row['password'];
	}

	if($user == $dbusername && $pass == $dbpassword)
	{
	session_start();
	$_SESSION['sess_user']=$user;

	/* Redirect browser */
	header("Location: member.php");
	}
	} else {
	echo "Invalid username or password!";
	}

} else {
	echo "All fields are required!";
}
}
?>
</font>
</center>
<p align=justify>
<center><font size=4 color=#FEFCFF>
<p>Poems of the Sangam literature contain numerous mentions of the various musical instruments such as the Seerkazhi , a stringed instrument of the Veena type and various percussion instruments such as murasu or muzham. Pattupattu contains a description of the yazh, a stringed instrument. There were two types of yaazh, Periyaazh or the 'large yaazh' contained 21 strings, whereas its more compact companion Siriyaazh had only seven strings. Two other types of yaazhs, Makarayaazh with 19 strings and Sakottuyaah with seven strings are also mentioned in Pattuppattu. However we have no further information on their actual appearance, mode of playing and the kind of melody generated by these instruments.</p>
<p>
The flute was the most popular wind instrument during the Sangam period. Perumpanarruppatai, one of the Pattupattu anthologies, describes the process of making the flute. The holes in the bamboo tube were bored using red-hot embers. The flute is also mentioned in the Kurincippattu as the instrument on which the shepherds played the ambal pann. Among the other wind instruments were the Pili, a small trumpet and Kanvidutumbu a larger flute ), perhaps producing lower octaves The flute also acted as a drone providing a constant pitch for vocalists and other instrumen('as long as the trunk of an elephant'ts.</p>
<p>
The Murasu, or the drum was the most popular percussion instrument. During festivals, the sound of Murasu conveyed joy and gaiety. Muzhavu, another percussion instrument accompanied singers. The drum was also used as the war-drum, calling people to arms. Mathuraikkanci mentions that the murasu was one of the prized possessions captured from the defeated enemy in the battlefield. Malaipatukatam describes the method of constructing and tuning the murasu. The sides were covered with skin, which were kept in position by leather straps. Malaipatukatam also mentions other percussion instruments such as udukkai, a palm-sized drum, Muzhavu, Siruparai and Tattai. The sound tattai resembled the croaking of a frog. This was a crude folk instrument made using a bamboo stick. Numerous slits were made across the stick and sound was produced on it by striking it on a stone or any other hard surface. In the Kurincippattu peasant women use tattai to scare the birds from the paddy field. A well-known percussion instrument is the mridangam(mathangam). It's a double headed drum used to accompany the veena(Yaazh) and the flute among other instruments.
</p><p>
List of Musical instruments used by ancient Tamil people was listed in Tirumurai[3] dated 6th to 11th century.
</p><p>
Akuli, Idakkai, Ilayam, Udukkai, Yezhil, Kathirikkai, Kandai, Karathalam, Kallalaku, Kalavadam, Kavil, Kazhal, Kalam, Kinai, Kinkini, Kilai, Kinnaram, Kudamuzha, Kuzhal, Kaiyalaku, Kokkarai, Kodukotti, Kottu, Kombu, Sangu, Sachari, Sanchalam, Salari, Siranthai, Silambu, Sinam, Thagunicham, Thakai, Thadari, Thattazhi, Thathalagam, Thandu, Thannumai, Thamarugam, Thaarai, Thaalam, Thuthiri, Thunthubi, Thudi, Thuriyam, Thimilai, Thondagam, Naral Surisangu, Padagam, Padutham, Panilam, Pambai, Palliyam, Parandai, Parai, Paani, Paandil, Pidavam, Perigai, Mathalam, Mani, Maruvam, Murasu, Muravam, Murugiyam, Murudu, Muzhavu, Monthai, Yaazl, Vangiyam, Vattanai, Vayir, Veenai, Veelai, Venkural.</p></center></font></p>
</body>
</html>